### PR TITLE
Feature run multiple queries

### PR DESCRIPTION
**Pull request by ssavvides**

### CODE REVIEW

**Comment by xystevensun** [comment]
Is this compatible with Spark 1.6.1?

**Comment by ssavvides** [comment]
I tested on Spark 2.0.0 which purports to be backward compatible, so it should.

**Comment by xystevensun** [comment]
Hi Savvas,

It seems that the createOrReplaceTempView method used in
./src/main/scala/TpchSchemaProvider.scala:125 is in Spark 2.0, not in Spark
1.6.1.
Is there an easy fix to make it compatible with Spark 1.6.1?

Thanks!

Best,
Xiaoye

**Comment by ssavvides** [comment]
If you are not planning to run any SQL statements (e.g. `sqlContext.sql("SELECT ...)`) then you can simply remove the lines: 
```
dfMap.foreach {
  case (key, value) => value.createOrReplaceTempView(key)
}
```

Otherwise, you can replace `createOrReplaceTempView` with `registerTempTable`.

**Comment by xystevensun** [comment]
It works!

Thanks!

Xiaoye

**Pull request merged**
